export const servicios = [
  { id: "1", nombre: "Alineado de Dirección" },
  { id: "2", nombre: "Balanceo y/o Rotación de Llantas" },
  { id: "3", nombre: "Revisión Pre-RTV" },
  { id: "4", nombre: "Revisión de Sistema de Suspensión" },
  { id: "5", nombre: "Revisión de Sistema de Dirección" },
  { id: "6", nombre: "Revisión/Mantenimiento Periódico por Kilometraje" },
  { id: "7", nombre: "Compra e Instalación de Llantas" },
  { id: "8", nombre: "Reparaciones Mayores (Indicar en las Observaciones)" },
  { id: "9", nombre: "Cambio de Aceite de Transmisión Man-Aut" },
  { id: "10", nombre: "Cambio de Aceite de Motor" },
  { id: "11", nombre: "Cambio de Fluido de Dirección Hidráulica" },
  { id: "12", nombre: "Limpieza de Inyectores" },
  { id: "13", nombre: "Cambio de Coolant" },
  { id: "14", nombre: "Cambio de Líquido de Frenos" },
  { id: "15", nombre: "Revisión y/o Cambio de Batería" },
  { id: "16", nombre: "Revisión/Ajuste/Limpieza de Frenos" },
  { id: "17", nombre: "Diagnóstico Scanner" },
  { id: "18", nombre: "Revisión de Frenos" },
  { id: "19", nombre: "Super Evaluación (28pts)" },
];